spring:
  application:
    name: lucas-agent
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: ${nacos.server-add}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        username: ${nacos.username}
        password: ${nacos.password}
      discovery:
        server-addr: ${nacos.server-add}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        username: ${nacos.username}
        password: ${nacos.password}

# Nacos 配置（通过环境变量注入）
nacos:
  namespace: ${NACOS_NAMESPACE}
  group: ${NACOS_GROUP}
  username: ${NACOS_USERNAME}
  password: ${NACOS_PASSWORD}
  server-add: ${NACOS_SERVER_ADD}
